<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-26 at 15:31:42.
 */
class Lengow_FeedTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_Feed
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Lengow_Feed('','','');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testTodo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
