<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-09 at 15:09:36.
 */
class Lengow_TranslationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_Translation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Lengow_Translation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lengow_Translation::t
     */
    public function testT()
    {
        $this->assertEquals("Missing Translation [hihi]", $this->object->t("hihi"));
        $this->assertEquals("Need some help?", $this->object->t("dashboard.screen.some_help_title"));
        $this->assertEquals("Select all of your products (5 products)",
            $this->object->t("product.screen.select_all_products", array("nb" => 5), "en_GB"));
        /*$this->object::$force_iso_code = 'fr_FR';
        $this->assertEquals("Need some help?", $this->object->t("dashboard.screen.some_help_title"));*/
    }

    /**
     * @covers Lengow_Translation::translate_final
     */
    public function testTranslate_final()
    {
        $fixture = New Fixture();
        $this->assertEquals('plop', $fixture->invokeMethod($this->object, "translate_final", array("plop", "")));
        $this->assertEquals('début wesh et 5 produits', $fixture->invokeMethod($this->object, "translate_final",
            array("début %{plop} et %{test} produits", array("plop" => "wesh", "test" => "5"))));

    }

    /**
     * @covers Lengow_Translation::load_file
     */
    public function testLoad_file()
    {
        $this->assertEquals(true, $this->object->load_file("fr_FR"));
        $this->assertEquals(false, $this->object->load_file("plop"));
    }
}
