<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-09 at 15:08:06.
 */
class Lengow_OrderTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Lengow_Order
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Lengow_Order;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Lengow_Order::get_id_order_from_lengow_orders
	 */
	public function testGet_id_order_from_lengow_orders() {
		$this->assertEquals( false, $this->object->get_id_order_from_lengow_orders( 'plop', 'plop', '2', '' ) );
	}

	/**
	 * @covers Lengow_Order::get_id_from_lengow_orders
	 * @todo   Implement testGet_id_from_lengow_orders().
	 */
	public function testGet_id_from_lengow_orders() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
