<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-04 at 17:07:33.
 */
class Lengow_Import_OrderTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Lengow_Import_Order
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
//        $array = array("marketplace" => "amazon", "marketplace_status" => "processing");
//        $data = (object) $array;
//
//        $this->object = new Lengow_Import_Order(
//            array(
//                'preprod_mode'        => 1,
//                'log_output'          => 1,
//                'marketplace_sku'     => 'marketplace_sku',
//                'delivery_address_id' => 'delivery_address_id',
//                'order_data'          => $data,
//                'package_data'        => $data,
//                'first_package'       => 'first_package'
//            ));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Lengow_Import_Order::import_order()
	 */
	public function testImport_order() {
		//$import_order = $this->object;
		//$fixture = New Fixture();

//        $this->assertEquals(5, $this->object->import_order());

	}

	/**
	 * @covers Lengow_Import_Order::_create_lengow_order()
	 */
	public function test_create_lengow_order() {
//        $import_order = $this->object;
//
//        $fixture = New Fixture();
		//print_r($fixture->invokeMethod($import_order, "_create_lengow_order", array("simple,plop,variable")));

		//$this->assertEquals(2, count($fixture->getInnerPropertyValueByReflection($import_order, '_product_types')));
	}
}
