<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-26 at 15:31:42.
 */
class Lengow_FileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Lengow_File('export');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lengow_File::get_link()
     */
    public function testGet_link()
    {
        $file = new Lengow_File('export', 'flux.csv');
        $this->assertEquals('http://example.org/wp-content/plugins/lengow-woocommerce/export/flux.csv', $file->get_link());
    }

    /**
     * @covers Lengow_File::get_path()
     */
    public function testGet_path()
    {
        $file = new Lengow_File('export', 'flux.csv');
        $this->assertContains('/lengow-woocommerce/export/flux.csv', $file->get_path());
    }

    /**
     * @covers Lengow_File::get_folder_path()
     */
    public function testGet_folder_path()
    {
        $file = new Lengow_File('export', 'flux.csv');
        $this->assertContains('/lengow-woocommerce/export', $file->get_folder_path());
    }

    /**
     * @covers Lengow_File::exists()
     */
    public function testExists()
    {
        $file = new Lengow_File('export', 'flux.csv');
        $this->assertEquals(true, $file->exists());

        $file = new Lengow_File('export', 'flux1.csv');
        unlink($file->get_path());
        $this->assertEquals(false, $file->exists());
    }

    /**
     * @covers Lengow_File::get_files_from_folder()
     */
    public function testGet_files_from_folder()
    {
        $file = new Lengow_File('export', 'flux.csv');

        $fixture = New Fixture();
        $this->assertEquals(2, count($fixture->invokeMethod($file, "get_files_from_folder", array("webservice"))));
        $this->assertEquals(false, $fixture->invokeMethod($file, "get_files_from_folder", array("plop")));
    }


}
