<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-04 at 17:07:33.
 */
class Lengow_Import_OrderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_Import_Order
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        /*$this->object = new Lengow_Import_Order(
            array(
                'preprod_mode'        => 1,
                'log_output'          => 1,
                'marketplace_sku'     => 'marketplace_sku',
                'delivery_address_id' => 'delivery_address_id',
                'order_data'          => 'order_data',
                'package_data'        => 'package_data',
                'first_package'       => 'first_package'
            ));*/
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lengow_Import_Order::import_order
     * @todo   Implement testImport_order().
     */
    public function testImport_order()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
