<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-04 at 17:31:38.
 */
class Lengow_InstallTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_Install
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Lengow_Install;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lengow_Install::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        $table_name = $wpdb->prefix . 'lengow_product2';
        $sql = 'CREATE TABLE IF NOT EXISTS ' . $table_name . ' ('
            . ' `id` INTEGER(11) NOT NULL AUTO_INCREMENT,'
            . ' `product_id` bigint(20) NOT NULL,'
            . ' PRIMARY KEY (`id`)) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;';
        dbDelta( $sql );

        $sql = 'SELECT column_name'
            . 'FROM information_schema.columns'
            . 'WHERE table_name=' . $table_name . ' and column_name=product_id';



        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lengow_Install::check_field_exists
     * @todo   Implement testCheck_field_exists().
     */
    public function testCheck_field_exists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lengow_Install::check_field_and_drop
     * @todo   Implement testCheck_field_and_drop().
     */
    public function testCheck_field_and_drop()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lengow_Install::rename_configuration_key
     * @todo   Implement testRename_configuration_key().
     */
    public function testRename_configuration_key()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lengow_Install::set_installation_status
     * @todo   Implement testSet_installation_status().
     */
    public function testSet_installation_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lengow_Install::is_installation_in_progress
     * @todo   Implement testIs_installation_in_progress().
     */
    public function testIs_installation_in_progress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
