<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-09 at 15:07:29.
 */
class Lengow_MarketplaceTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Lengow_Marketplace
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		//$this->object = new Lengow_Marketplace('plop');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Lengow_Marketplace::get_state_lengow
	 */
	public function testGet_state_lengow() {
		//$this->assertEquals(7, $this->object->get_state_lengow());
	}
}
