<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-26 at 15:18:53.
 */
class Lengow_ConnectorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Lengow_Connector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Lengow_Connector('','');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Lengow_Connector::get_access_id
     */
    public function testGet_access_id()
    {
        $connector = new Lengow_Connector('lengow_access_token', 'lengow_secret_token');
        Lengow_Configuration::update_value('lengow_account_id', '1111');
        Lengow_Configuration::update_value('lengow_access_token', 'lengow_access_token');
        Lengow_Configuration::update_value('lengow_secret_token', 'lengow_secret_token');

        $this->assertEquals(array( '1111', 'lengow_access_token', 'lengow_secret_token' ), $connector->get_access_id());

        Lengow_Configuration::update_value('lengow_account_id', null);
        Lengow_Configuration::update_value('lengow_access_token', 'lengow_access_token');
        Lengow_Configuration::update_value('lengow_secret_token', 'lengow_secret_token');

        $this->assertEquals(array( null, null, null ), $connector->get_access_id());

    }


}
